spring:
  main:
    web-application-type: none
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/new_morandi?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Pepsi1943@


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
        use_sql_comments: true

    batch:
      job:
        enabled: false

